"""Initial schema

Revision ID: 676783b88dfe
Revises: 
Create Date: 2025-11-16 12:57:09.575206

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '676783b88dfe'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stat_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('abbreviation', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stat_types_name'), 'stat_types', ['name'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('abbrev', sa.String(length=10), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_external_id'), 'teams', ['external_id'], unique=True)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('season', sa.String(length=20), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('spread', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_external_id'), 'games', ['external_id'], unique=True)
    op.create_index(op.f('ix_games_game_date'), 'games', ['game_date'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('position', sa.String(length=10), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_external_id'), 'players', ['external_id'], unique=True)
    op.create_index(op.f('ix_players_name'), 'players', ['name'], unique=False)
    op.create_table('prop_markets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sportsbook', sa.String(length=50), nullable=False),
    sa.Column('market_name', sa.String(length=100), nullable=False),
    sa.Column('stat_type_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stat_type_id'], ['stat_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_markets_sportsbook'), 'prop_markets', ['sportsbook'], unique=False)
    op.create_table('box_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Float(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('assists', sa.Integer(), nullable=True),
    sa.Column('rebounds', sa.Integer(), nullable=True),
    sa.Column('steals', sa.Integer(), nullable=True),
    sa.Column('blocks', sa.Integer(), nullable=True),
    sa.Column('turnovers', sa.Integer(), nullable=True),
    sa.Column('three_pointers_made', sa.Integer(), nullable=True),
    sa.Column('field_goals_made', sa.Integer(), nullable=True),
    sa.Column('field_goals_attempted', sa.Integer(), nullable=True),
    sa.Column('free_throws_made', sa.Integer(), nullable=True),
    sa.Column('free_throws_attempted', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_box_scores_game_id'), 'box_scores', ['game_id'], unique=False)
    op.create_index(op.f('ix_box_scores_player_id'), 'box_scores', ['player_id'], unique=False)
    op.create_table('injury_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_injury_reports_player_id'), 'injury_reports', ['player_id'], unique=False)
    op.create_index(op.f('ix_injury_reports_report_date'), 'injury_reports', ['report_date'], unique=False)
    op.create_table('player_game_features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('stat_type_id', sa.Integer(), nullable=False),
    sa.Column('feature_schema_version', sa.Integer(), nullable=False),
    sa.Column('feature_vector', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['stat_type_id'], ['stat_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_game_features_game_id'), 'player_game_features', ['game_id'], unique=False)
    op.create_index(op.f('ix_player_game_features_player_id'), 'player_game_features', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_game_features_stat_type_id'), 'player_game_features', ['stat_type_id'], unique=False)
    op.create_table('props',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('stat_type_id', sa.Integer(), nullable=False),
    sa.Column('sportsbook', sa.String(length=50), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('prop_date', sa.Date(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ),
    sa.ForeignKeyConstraint(['stat_type_id'], ['stat_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_props_game_id'), 'props', ['game_id'], unique=False)
    op.create_index(op.f('ix_props_player_id'), 'props', ['player_id'], unique=False)
    op.create_index(op.f('ix_props_prop_date'), 'props', ['prop_date'], unique=False)
    op.create_index(op.f('ix_props_sportsbook'), 'props', ['sportsbook'], unique=False)
    op.create_index(op.f('ix_props_stat_type_id'), 'props', ['stat_type_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('over_odds', sa.Integer(), nullable=False),
    sa.Column('under_odds', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['prop_id'], ['props.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_snapshots_prop_id'), 'odds_snapshots', ['prop_id'], unique=False)
    op.create_index(op.f('ix_odds_snapshots_timestamp'), 'odds_snapshots', ['timestamp'], unique=False)
    op.create_table('prop_predictions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('run_id', sa.String(length=100), nullable=False),
    sa.Column('predicted_mean', sa.Float(), nullable=False),
    sa.Column('predicted_variance', sa.Float(), nullable=False),
    sa.Column('prob_over', sa.Float(), nullable=False),
    sa.Column('prob_under', sa.Float(), nullable=False),
    sa.Column('edge_over', sa.Float(), nullable=False),
    sa.Column('edge_under', sa.Float(), nullable=False),
    sa.Column('ev_over', sa.Float(), nullable=False),
    sa.Column('ev_under', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['prop_id'], ['props.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prop_predictions_created_at'), 'prop_predictions', ['created_at'], unique=False)
    op.create_index(op.f('ix_prop_predictions_prop_id'), 'prop_predictions', ['prop_id'], unique=False)
    op.create_index(op.f('ix_prop_predictions_run_id'), 'prop_predictions', ['run_id'], unique=False)
    op.create_table('posted_plays',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prop_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('side', sa.String(length=10), nullable=False),
    sa.Column('odds_at_post', sa.Integer(), nullable=False),
    sa.Column('edge_at_post', sa.Float(), nullable=False),
    sa.Column('posted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('result', sa.String(length=10), nullable=True),
    sa.Column('actual_value', sa.Float(), nullable=True),
    sa.Column('graded_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['prediction_id'], ['prop_predictions.id'], ),
    sa.ForeignKeyConstraint(['prop_id'], ['props.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posted_plays_posted_at'), 'posted_plays', ['posted_at'], unique=False)
    op.create_index(op.f('ix_posted_plays_prop_id'), 'posted_plays', ['prop_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posted_plays_prop_id'), table_name='posted_plays')
    op.drop_index(op.f('ix_posted_plays_posted_at'), table_name='posted_plays')
    op.drop_table('posted_plays')
    op.drop_index(op.f('ix_prop_predictions_run_id'), table_name='prop_predictions')
    op.drop_index(op.f('ix_prop_predictions_prop_id'), table_name='prop_predictions')
    op.drop_index(op.f('ix_prop_predictions_created_at'), table_name='prop_predictions')
    op.drop_table('prop_predictions')
    op.drop_index(op.f('ix_odds_snapshots_timestamp'), table_name='odds_snapshots')
    op.drop_index(op.f('ix_odds_snapshots_prop_id'), table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_props_stat_type_id'), table_name='props')
    op.drop_index(op.f('ix_props_sportsbook'), table_name='props')
    op.drop_index(op.f('ix_props_prop_date'), table_name='props')
    op.drop_index(op.f('ix_props_player_id'), table_name='props')
    op.drop_index(op.f('ix_props_game_id'), table_name='props')
    op.drop_table('props')
    op.drop_index(op.f('ix_player_game_features_stat_type_id'), table_name='player_game_features')
    op.drop_index(op.f('ix_player_game_features_player_id'), table_name='player_game_features')
    op.drop_index(op.f('ix_player_game_features_game_id'), table_name='player_game_features')
    op.drop_table('player_game_features')
    op.drop_index(op.f('ix_injury_reports_report_date'), table_name='injury_reports')
    op.drop_index(op.f('ix_injury_reports_player_id'), table_name='injury_reports')
    op.drop_table('injury_reports')
    op.drop_index(op.f('ix_box_scores_player_id'), table_name='box_scores')
    op.drop_index(op.f('ix_box_scores_game_id'), table_name='box_scores')
    op.drop_table('box_scores')
    op.drop_index(op.f('ix_prop_markets_sportsbook'), table_name='prop_markets')
    op.drop_table('prop_markets')
    op.drop_index(op.f('ix_players_name'), table_name='players')
    op.drop_index(op.f('ix_players_external_id'), table_name='players')
    op.drop_table('players')
    op.drop_index(op.f('ix_games_game_date'), table_name='games')
    op.drop_index(op.f('ix_games_external_id'), table_name='games')
    op.drop_table('games')
    op.drop_index(op.f('ix_teams_external_id'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_stat_types_name'), table_name='stat_types')
    op.drop_table('stat_types')
    # ### end Alembic commands ###
